apiVersion: apps/v1
kind: Deployment
metadata:
  name: skyward-master-stg
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skyward-master-stg
  template:
    metadata:
      labels:
        app: skyward-master-stg
    spec:
      containers:
      - name: skyward-master-stg
        image: skywardacrdev.azurecr.io/skywardmasterdata:stg
          # command: ["/bin/sh", "-c"]
          # args:
          #   - "ls -lah /app;"
        resources:
          limits:
            cpu: 150m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: skyward-master-stg-svc
  namespace: staging
spec:
  selector:
    app: skyward-master-stg
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000